se agrega workflow

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -1,11 +1,16 @@
-name: Standalone CLI
+name: Skims Standalone CLI
 on: [push, pull_request]
+
 jobs:
   machineStandalone:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
-      - uses: docker://docker.io/fluidattacks/skims:latest
-        name: skimsStandalone
-        with:
-          args: skims scan /
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Run Fluid Attacks Skims
+        run: |
+          docker run --rm -v ${{ github.workspace }}:/my-dir fluidattacks/skims:latest skims scan /my-dir || {
+            echo "❌ Skims found vulnerabilities or failed during analysis"
+            exit 1
+          }
